name: Rust DevOps Pipeline

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Rust
      uses: actions/setup-rust@v1
    
    - name: Build
      run: cargo build
    
    - name: Run executable
      run: ./target/debug/hello
