name: Rust DevOps Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on changes to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo install cargo-tree
        shell: bash  # Use bash shell for running the script

      - name: Build Rust Code
        run: cargo build --verbose

      - name: Run Tests and Reject PR if Fails
        run: |
          cargo test --verbose
          test_result=$?
          if [ $test_result -ne 0 ]; then
            echo "Tests failed. Rejecting PR."
            exit 1
          fi
