trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu agent for building

steps:
  - script: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y  # Install Rust
      source $HOME/.cargo/env  # Add Cargo to the PATH
    displayName: 'Install Rust'

  - script: |
      cargo build --verbose  # Build the Rust project
    displayName: 'Build'

  - script: |
      cargo test --verbose  # Run tests
    displayName: 'Run Tests'
