name: Rust DevOps Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on changes to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repository

      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo install cargo-tree
        shell: bash  # Use bash shell for running the script

      - name: Build Rust Code
        run: cargo build --verbose

      - name: Run Executable
        run: .\target\debug\hello  # Replace `your_executable_name` with the actual name of your executable
