name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build project
        run: cargo build

      - name: Run tests
        run: cargo test
