name: Rust DevOps Pipeline

on:
  push:
    branches:
      - main
    schedule:
      - cron: "45 11 * * *"  # Every day at 11:45 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Rust project
        run: cargo build

      - name: Run executable
        run: ./target/debug/hello

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-executable
          path: ./target/debug/hello

  execute:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-executable
          path: ./target/debug/

      - name: Run executable
        run: |
          chmod +x ./target/debug/hello
          ./target/debug/hello

