name: Rust DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use Node.js 20

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build Rust project
        run: cargo build

      - name: Run executable
        run: .\target\debug\hello

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-executable
          path: .\target\debug\hello

  execute:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use Node.js 20

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-executable
          path: .\target\debug\

      - name: Run executable
        run: .\target\debug\hello
