# .github/workflows/rust.yml

name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 'stable'

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test

    - name: Run Hello World
      run: cargo run
